import { Data, IProductInput } from "@/types"
import { toSlug } from "./utils"

const products: IProductInput[] = [
    // Rings 
    {
      name: 'Urban Muse Stackable Ring',
      slug: toSlug ('urban-muse-stackable-rings'),
      category: 'Rings',
      subCategory: 'Daily Wear',
      images: ['/images/r_daily_1.jpg', '/images/r_daily_2.jpg'],
      tags: ['new-arrival', 'featured'],
      isPublished: true,
      price: 199,
      listPrice: 299,
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      numSales: 9,
      countInStock: 11,
      description: [
        "Stylish and lightweight stackable ring set, perfect for daily wear.",
        "Crafted from skin-safe, environment-friendly materials.",
        "Sleek minimalist design for versatile styling.",
        "Ideal for casual wear, office, or gifting.",
        "Available in standard Indian ring sizes (in mm diameter) for a perfect fit."
      ],      
      sizes: [ '12', '14', '16', '18', '20'],
      colors: ['Rose Gold', 'Sterling Silver', 'Midnight Black'],
  
      reviews: [],
    },
    {
      name: 'Signature Cocktail Ring',
      slug: toSlug('signature-cocktail-ring'),
      category: 'Rings',
      subCategory: 'Office Wear',
      images: [
        '/images/r_office_1.jpg',
        '/images/r_office_2.jpg'
      ],
      tags: ['featured'],
      isPublished: true,
      price: 299,
      listPrice: 349,
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 29,
      countInStock: 12,
      description: [
        'Elegant and bold cocktail ring, designed for professional office wear.',
        'Crafted with high-quality materials, ensuring both durability and comfort.',
        'Sophisticated design perfect for adding a statement to office attire.',
        'Ideal for business meetings, office events, or as a stylish accessory for work.',
        'Available in standard Indian ring sizes (in mm diameter) for a perfect fit.',
      ],
      sizes: ['14', '15', '16', '17', '18', '20'],
      colors: ['Platinum Frost ', 'Champagne Gold', 'Dusty Mauve'],
  
      reviews: [],
    },
    {
      name: "Twinkle Mini Adjustable Rings",
      slug: toSlug('twinkle-mini-adjustable-rings'),
      category: 'Rings',
      subCategory: 'Kids Wear',
      images: ['/images/r_kids_1.jpg', '/images/r_kids_2.jpg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 99,
      listPrice: 199,
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 55,
      countInStock: 13,
      description:[
        'Colorful and adjustable rings, designed especially for kids who love to accessorize.',
        'Crafted with skin-safe, child-friendly materials to ensure all-day comfort and safety.',
        'Fun and vibrant colors make these rings a delightful addition to any outfit.',
        'Adjustable design ensures a perfect fit as your child grows.',
        'Ideal for birthdays, return gifts, or playful everyday wear.',
      ],
      sizes: ['10', '12', '14', '16', '18'],
      colors: ['Emerald Green', 'Blush Rose', 'Sapphire Blue '],
  
      reviews: [],
    },
    {
      name: 'SoulLink™ Engraved Couple Rings Set',
      slug: toSlug('soullink-engraved-couple-rings'),
      category: 'Rings',
      subCategory: 'Customized',
      images: [
        '/images/r_customised_1.jpg',
         '/images/r_customised_2.jpg',
         '/images/r_customised_3.jpg',
        ],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 499,
      listPrice: 599,
      avgRating: 4.85,
      numReviews: 26,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 54,
      countInStock: 14,
      description:[
      ],
      sizes: [
        'Women - 14',
        'Women - 15',
        'Women - 16',
        'Women - 17',
        'Men - 18',
        'Men - 19',
        'Men - 20',
        'Men - 21'
      ],     
      colors: ['Champagne Gold', 'Platinum Silver'],

      reviews: [],
    },
    // Necklaces
    {
      name: 'Urban Grace Minimalist Necklace',
      slug: toSlug('urban-grace-minimalist-necklace'),
      category: 'Necklaces',
      subCategory: 'Daily Wear',
      images: ['/images/n_daily_1.jpg', '/images/n_daily_2.jpg', '/images/n_daily_3.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 299,
      listPrice: 499,
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      countInStock: 54,
      numSales: 21,
      description:[
        "Chic and lightweight necklace, perfect for everyday elegance.",
        "Crafted with skin-safe, tarnish-resistant materials for long-lasting shine.",
        "Minimalist pendant design that complements both western and ethnic wear.",
        "Ideal for daily use, casual outings, or thoughtful gifting.",
        "Available in multiple chain lengths (in inches) to suit all age groups and necklines."
      ],
      sizes: ['14', '16', '18' , '20', '22'],
      colors: ['Moonlit Silver', 'Deep Sapphire', 'Pearl White', 'Rose Blush'],
  
      reviews: [],
    },
    {
      name: 'Seraphine Layered Chain Necklace',
      slug: toSlug('Seraphine Layered Chain Necklace'),
      category: 'Necklaces',
      subCategory: 'Office Wear',
      images: ['/images/n_office_1.png', '/images/n_office_2.jpg'],
      tags: ['featured', 'todays-deal'],
      isPublished: true,
      price: 399,
      listPrice: 799,
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 1 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 22,
      numSales: 54,
      description:[
        "Elegant double-layered chain necklace designed for effortless style.",
        "Crafted from hypoallergenic, tarnish-resistant materials for all-day comfort.",
        "Minimalist yet bold — ideal for workwear, casual, and semi-formal outfits.",
        "Smooth clasp design ensures a secure and adjustable fit.",
        "Available in standard chain lengths (in inches) to suit various necklines and occasions."
      ],
      sizes: ['16', '18', '20', '22'],
      colors: ['Champagne Gold', 'Antique Silver', 'Graphite Black'],
  
      reviews: [],
    },
    {
      name: 'Flower Petal Party Choker',
      slug: toSlug('flower-petal-party-choker'),
      category: 'Necklaces',
      subCategory: 'Party Wear',
      images: ['/images/n_chockers_party_1.webp', '/images/n_chockers_party_2.webp'],
      tags: ['best-seller'],
      isPublished: true,
      price: 499,
      listPrice: 899,
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 23,
      numSales: 54,
      description:[
        "Elegant choker necklace crafted for evening and party occasions.",
        "Designed with skin-friendly materials for long-lasting comfort and style.",
        "Statement-making silhouette with a refined touch of glam.",
        "Perfect for cocktail parties, weddings, or festive events.",
        "Available in popular choker lengths(in inches) to match all necklines and styling preferences."
      ],
      sizes: ['12', '14', '16', '18', '20'],
      colors: ['Crimson Wine', 'Pearl Beige'],
  
      reviews: [],
    },
    {
      name: 'BohoSoul Layered Pendant Necklace',
      slug: toSlug('bohosoul-layered-pendant-necklace'),
      category: 'Necklaces',
      subCategory: 'Indo-Western',
      images: ['/images/n_indo_1.jpg', '/images/n_indo_2.jpg', '/images/n_indo_3.jpg'],
      tags: ['todays-deal'],
      isPublished: true,
      price: 399,
      listPrice: 799,
      avgRating: 3.85,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 24,
      numSales: 53,
      description:[


      ], 
      sizes: ['18', '20', '22', '24'],
      colors: ['Burnt Copper', 'Turquoise Mist', 'Vintage Gold'],
  
      reviews: [],
    },
    {
      name: "SignatureGlow Custom Name Pendant", 
      slug: toSlug("singatureglow-custom-name-pendant"),
      category: 'Necklace',
      subCategory: 'Customized',
      images: ['/images/n_customised.jpg'],
      tags: ['todays-deal'],
      isPublished: true,
      price: 499,
      listPrice: 999,
      avgRating: 4.02,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 24,
      numSales: 53,
      description:[
        "Elegant name necklace personalized with your choice of text.",
        "Crafted with durable, skin-safe, nickel-free metal plating.",
        "Perfect for gifting, daily styling, or as a signature accessory.",
        "Lightweight and adjustable chain for a comfortable fit.",
        "Available in classic finishes to suit every skin tone and outfit."
      ],
      sizes: ['16', '18', '20', '22', '24'],
      colors: ['Rose Gold', 'Classic Silver'],
  
      reviews: [],
    },
    // Braclets
    {
      name: "SerenGlow Everyday Bangles",
      slug: toSlug("serenglow-everyday-bangles"),
      category: 'Braclets & Bangles',
      subCategory: 'Daily Wear',
      images: ['/images/b_daily_1.jpg', '/images/b_daily_2.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 699,
      listPrice: 1199,
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 5 },
        { rating: 5, count: 5 },
      ],
      countInStock: 31,
      numSales: 48,
      description:[
        "Elegant combo of daily wear bracelets and bangles in a timeless design.",
        "Crafted from skin-safe, tarnish-resistant metal for long-lasting wear.",
        "Versatile styles suitable for office, casual, and festive occasions.",
        "Smooth inner edges for comfortable all-day use.",
        "Available in standard Indian bangle sizes for the perfect wrist fit."
      ],
      sizes: ['2.2', '2.4', '2.6', '2.8', '2.10'],
      colors: ['Antique Bronze', 'Ivory White'],
  
      reviews: [],
    },
    {
      name: 'Celeste Whisper Office Charm Bracelet',
      slug: toSlug(
        'celeste-whisper-office-charm-bracelet'
      ),
      category: 'Braclets & Bangles',
      subCategory: 'Office Wear',
      images: ['/images/b_office_1.webp', '/images/b_office_2.webp'],
      tags: ['featured'],
      isPublished: true,
      price: 399,
      listPrice: 799,
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 32,
      numSales: 48,
      description:[
        "Elegant charm bracelet designed for modern office and everyday wear.",
        "Crafted from premium anti-tarnish alloy with a smooth polished finish.",
        "Features symbolic charms to add a touch of personality to your outfit.",
        "Lightweight, skin-friendly, and adjustable for a perfect wrist fit.",
        "Ideal for gifting, casual meetings, or subtle professional styling."
      ], 
      sizes: ['5.5', '7.5'],
      colors: ['Polished Silver', 'Matte Charcoal', 'Muted Rose'],
  
      reviews: [],
    },
    {
      name: 'Aurora Hand Harness Bracelet',
      slug: toSlug(
        'aurora-hand-harness-bracelet'
      ),
      category: 'Braclets & Bangles',
      subCategory: 'Party Wear',
      images: ['/images/b_party_1.jpg', '/images/b_party_2.jpg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 899,
      listPrice: 2999,
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 33,
      numSales: 48,
      description:[
        "Stylish hand harness bracelet perfect for festive and party wear.",
        "Crafted with anti-tarnish metal and detailed chainwork.",
        "Adorned with intricate embellishments for an elegant statement look.",
        "Skin-friendly, lightweight, and adjustable for a comfortable fit.",
        "Ideal for weddings, ethnic celebrations, or gifting."
      ], 
      sizes: ['5.5', '7.5'],
      colors: ['Golden Beige', 'Antique Silver'],
  
      reviews: [],
    },
    {
      name: 'Mystic Bead Charm Bracelet',
      slug: toSlug(
        'mystic-bead-charm-bracelet'
      ),
      category: 'Braclets & Bangles',
      subCategory: 'Indo-Western',
      images: ['/images/b_indo_1.jpg', '/images/b_indo_2.jpg'],
      tags: ['todays-deal'],
      isPublished: true,
      price: 399,
      listPrice: 699,
      avgRating: 3.85,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 34,
      numSales: 48,
      description:[

      ],  
      sizes: ['5.5', '7.5'],
      colors: ['Teal Frost', 'Copper Bronze', 'Matte Gold'],
  
      reviews: [],
    },
    {
      name: 'Twinkle Charms Kids Bracelet',
      slug: toSlug('twinkle-charms-kids-bracelet'),
      category: 'Braclets & Bangles',
      subCategory: 'Kids Wear',
      images: ['/images/b_kids_1.jpg', '/images/b_kids_2.jpg', '/images/b_kids_3.jpg'],
      tags: ['new-arrival', 'featured'],
      isPublished: true,
      price: 499,
      listPrice: 899,
      avgRating: 3.66,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 35,
      numSales: 48,
      description:[
        "Adorable charm bracelet designed especially for kids aged 4–12.",
        "Crafted from child-safe, hypoallergenic materials for all-day comfort.",
        "Features playful charms and bright colors to match every outfit.",
        "Adjustable sizing for a snug and flexible fit.",
        "Perfect for birthdays, return gifts, or festive wear."
      ],
      sizes: ['S', 'M', 'L'],
      colors: ['Candy Pink', 'Ocean Teal', 'Sunshine Yellow'],
  
      reviews: [],
    },
    {
      name: 'Engraved Name Bracelet Cuff',
      slug: toSlug('engraved-name-bracelet-cuff'),
      category: 'Braclets & Bangles',
      subCategory: 'Customized',
      images: ['/images/b_customised_1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 899,
      listPrice: 1499,
      avgRating: 3.46,
      numReviews: 13,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 36,
      numSales: 49,
      description:[
        "Make your mark with our Engraved Name Bracelet—crafted for those who love meaningful, personalized jewelry.",
        "Features custom engraving of names, initials, or dates on a sleek metal finish.",
        "Comfortable cuff design with adjustable fit for most wrist sizes.",
        "Perfect gift for anniversaries, birthdays, or couple keepsakes.",
        "Crafted with durable, anti-tarnish materials for everyday elegance."
      ],
      sizes: ['6', '7', '8'],
      colors: ['Brown', 'Sliver', 'Black'],
  
      reviews: [],
    },
    // Anklets 
    {
      name: 'Classic Daily Wear Anklet',
      slug: toSlug(
        'classic-daily-wear-anklet'
      ),
      category: 'Anklets',
      subCategory: 'Daily Wear',
      images: ['/images/a_daily_1.jpg', '/images/a_daily_2.jpg'],
      tags: ['featured'],
      isPublished: true,
      price: 399,
      listPrice: 799,
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 42,
      numSales: 50,
      description: [
        "Elevate your everyday look with this Classic Daily Wear Anklet—crafted for comfort and charm.",
        "Lightweight and minimalistic design, perfect for daily use.",
        "Secure clasp ensures a reliable fit throughout the day.",
        "Suitable for casual wear, office, and light outings.",
        "A must-have staple in every jewelry collection."
      ],
        
      sizes: ['9', '10'],
      colors: ['Silver', 'Rose Gold', 'Oxidized Black'],
  
      reviews: [],
    },
    {
      name: 'Everyday Kids Charm Anklet',
      slug: toSlug('everyday-kids-charm-anklet'),
      category: 'Anklets',
      subCategory: 'Daily Wear',
      images: ['/images/a_kids_1.jpg', '/images/a_kids_2.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 199,
      listPrice: 699,
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      countInStock: 41,
      numSales: 48,
      description:[
        "Delicate and delightful, this kids anklet is designed for playful days and sweet moments.",
        "Made from skin-friendly materials for comfort and safety.",
        "Secure clasp and lightweight build ideal for everyday wear.",
        "Perfect for birthdays, casual outings, or gifting your little one.",
        "Adds a soft sparkle to every tiny step."
      ],
      sizes: ['6', '7'],
      colors: ['Silver', 'Light Pink', 'Sky Blue'],
  
      reviews: [],
    },
]

const data : Data = {
    products,
    headerMenus: [
        {
            name: "Today's Deal",
            href: '/search?tag=todays-deal',
        },
        {
            name: 'New Arrivals',
            href: '/search?tag=new-arrival',
        },
        {
            name: 'Featured Products',
            href: '/search?tag=featured',
        },
        {
            name: 'Best Sellers',
            href: '/search?tag=best-seller',
        },
        {
            name: 'Browsing History',
            href: '/#browsing-history',
          },
        {
            name: 'Customer Service',
            href: '/page/customer-service',
        },
        {
            name: 'About Us',
            href: '/page/about-us',
        },
        {
            name: 'Help',
            href: '/page/help',
        },
    ],

    carousels: [
        {
            title: 'Most popular Rings for Sale',
            buttonCaption: 'Shop Now',
            image: '/images/banner2.jpg',
            url: '/search?category=Rings',
            isPublished: true,
        },
        {
            title: 'Best Sellers in Necklaces',
            buttonCaption: 'Shop Now',
            image: '/images/banner1.jpg',
            url: '/search?category=Necklaces',
            isPublished: true,
        },
        {
            title: 'Best Deals on Braclets',
            buttonCaption: 'Shop Now',
            image: '/images/banner3.jpg',
            url: '/search?category=Rings',
            isPublished: true,
        },
    ],


}

export default data